### PR TITLE
Use argparse

### PR DESCRIPTION
**Pull request by pumazi**
Use [argparse](https://docs.python.org/3/library/argparse.html) for commandline argument parsing.

This improves some of the maintainability of the code. I'd recommend you go through the commits one at a time. I've added ancillary information in the extended commit message which could be useful for explaining the changes.

The most notable improvement here is that it will no longer open a browser window.

### CODE REVIEW

**Comment by kerwinso** [comment]
Please document how to use this version of the tool (arguments, etc.), preferably with examples.

**Comment by pumazi** [comment]
Try: `python batch-build-pdf.py --help`

**Comment by pumazi** [comment]
I've tried to arrange the commits in such a way that you should be able to walk through them. If you look at each change one at a time, I think you'll get a better understanding.

**Comment by kerwinso** [comment]
If I run ` python batch-build-pdf.py -s dev input.txt`, I get the following error:
```
Traceback (most recent call last):
  File "batch-build-pdf.py", line 63, in <module>
    main()
  File "batch-build-pdf.py", line 51, in main
    buildurl = urljoin(baseURL + "/col" + "{}/latest/enqueue".format(collID))
TypeError: urljoin() takes at least 2 arguments (1 given)
```

**Comment by pumazi** [comment]
Oops. Documentation for that function is at https://docs.python.org/2.7/library/urlparse.html#urlparse.urljoin

You'll want to maybe change that line to `urljoin(baseURL, "/col{}/latest/enqueue".format(collID))`.

**Comment by kerwinso** [comment]
OK, so let me get this straight.

First off, you re-write my code into something totally different and unrecognizable that I can no longer maintain, without any input from me or my users... because it "relaxes" you.

Second, you change the user interface without properly documenting it or consulting with me.

Third, the new "improved" tool doesn't even *work* (see errors above).

Lastly: you're asking *me* to fix *your* broken code.

That's rich, man. Really rich.

**Comment by pumazi** [comment]
My apologies. I'm ill at the moment, so I didn't make the change myself. :mask:

To contest your second point, I did split the pull request into #4 (no interface changes) and #5 (this pull request).

My pardons for the error. Sometimes these things happen.

Sorry to have caused you any unnecessary anxiety. I was only trying to provide you with commits that may aid in your learning of python. 😰

**Pull request closed without merging**
